# Generated by Django 5.2.7 on 2025-12-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=150)),
                ('service_desc', models.TextField()),
                ('service_read_link', models.CharField(max_length=150)),
            ],
        ),
    ]
