# Generated by Django 5.2.7 on 2025-12-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourservice', '0002_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='description',
            new_name='about_description',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='title',
            new_name='about_title',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='about_feature1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='about_feature2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='about_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='About'),
        ),
    ]
