# Generated by Django 5.2.7 on 2025-12-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourservice', '0003_contactform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_read_link',
        ),
        migrations.AddField(
            model_name='service',
            name='service_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='service'),
        ),
    ]
