# Generated by Django 5.2.7 on 2025-12-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourservice', '0004_remove_service_service_read_link_service_service_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_proffession', models.CharField()),
                ('review_description', models.TextField()),
                ('review_img', models.FileField(default=None, max_length=250, null=True, upload_to='review')),
                ('review_name', models.CharField()),
            ],
        ),
    ]
