# Generated by Django 5.2.7 on 2025-12-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourservice', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_proffession',
            field=models.CharField(max_length=100),
        ),
    ]
